### ISSUE TITLE
If master.m3u8 contains the URI to the encryption key, it is converted to an IPFS link!

### ISSUE THREAD

**Issue by gluneau** [moshisushi/hlsjs-ipfs-loader#22]
The file master.m3u8 contains the URI to the encryption key
`#EXT-X-KEY:METHOD=AES-128,URI="https://hlsbook.net/enc.key",IV=0xecd0d06eaf884d8226c33928e87efa33`

Here is the error in the console:
```
Error: File not found: Qma4qsd4h5PY7YmxHgva1w68FMcPv4c8fBR5LjUwfzZEzq/enc.key
    at getFile (index.js:125)
```

In a context where a video is encrypted, it does not make sense to include the key in the ipfs directory itself.
The URI should remain https and not become ipfs.

**Comment by vaultec81** [comment]
See https://github.com/moshisushi/hlsjs-ipfs-loader/issues/21 for continued discussion.
