### ISSUE TITLE
How to port the IPFS streaming example to React App?

### ISSUE THREAD

**Issue by FabioNevesRezende** [moshisushi/hlsjs-ipfs-loader#28]
I'm trying to build an equivalent of the example for [streaming](https://github.com/ipfs/js-ipfs/tree/master/examples/browser-video-streaming) but I don't know exactly how to rewrite the code to a nodejs react application. So far I've wrote this react component:

```
import React, {Component} from "react";
const Ipfs = require('ipfs')

const HlsLib = require('hlsjs-ipfs-loader')

class Watch extends Component{

    async videoEventListener(){
        const testHash = 'QmdpAidwAsBGptFB3b6A9Pyi5coEbgjHrL3K2Qrsutmj9K'
        const repoPath = 'ipfs-' + Math.random()
        const node = await Ipfs.create({ repo: repoPath })
      
        Hls.DefaultConfig.loader = HlsjsIpfsLoader
        Hls.DefaultConfig.debug = false
        if (Hls.isSupported()) {
          const video = document.getElementById('video')
          const hls = new Hls()
          hls.config.ipfs = node
          hls.config.ipfsHash = testHash
          hls.loadSource('master.m3u8')
          hls.attachMedia(video)
          hls.on(Hls.Events.MANIFEST_PARSED, () => video.play())
        }
    } 

    render(){
        return (
            <div>
                
                <video id="video" controls></video>
            </div>
        );
    }

```
}

Since in the example we got the html script tag which gave scope to the variables `hls` `Hls`, etc inside  `videoEventListener`. So how to obtain this scope from the `HlsLib` installed with `npm i hlsjs-ipfs-loader`

**Comment by vaultec81** [comment]
I believe you can obtain `HlsLib` in a similar fashion to how you would use any other module/library... Your code looks alright. However, you need to call `this.videoEventListener()` from somewhere, preferably from the `componentDidMount()` hook. You can should also replace `id="video"` and `document.getElementById('video')` with [react refs](https://reactjs.org/docs/refs-and-the-dom.html).
