### ISSUE TITLE
Does this work together with ipfsd-ctl connected to go-ipfs?

### ISSUE THREAD

**Issue by Powersource** [moshisushi/hlsjs-ipfs-loader#4]
I could try myself but I'm kind of busy. At first sight it looks like it shouldn't be a problem?

Good job here btw, looks great! Been looking for this kind of thing for a while (this reinforces my belief that the ipfs ecosystem is good but too chaotically documented :P).

**Comment by moshisushi** [comment]
Hey and thanks!

I don't think I understand the question though: js-ipfsd-ctl is just a remote control for the ipfs daemon so it shouldn't interfere with any of this... the important thing if you want to stream directly from your ipfs node (daemon) is to make sure it's got a secure websocket listener running. You can then add it explicitly to the swarm from js-ipfs.

Hope that helps!

**Comment by Powersource** [comment]
Yes it shouldn't be a problem, I was just thinking if js-ipfs and go-ipfs (or the api) differ in any way that would interfere with this (e.g. js-ipfs doesn't have ipns yet). But afaict the go-ipfs features are pretty much a superset of the js features.

Thanks, I'll open another issue if I run into any problems :)
