### ISSUE TITLE
m3u8 pub and sub

### ISSUE THREAD

**Issue by segator** [moshisushi/hlsjs-ipfs-loader#5]
Nice work, for first step.
I think the next step is live streaming and  notify user new segments are genereted through ipfs pubsub

maybe every time the host publish, can publish entire m3u8.

client provide the latest published m3u8.
This could work, what I'm not sure is the "latency" between the host push the new m3u and the clients get the message, it's enough fast

**Comment by moshisushi** [comment]
I don't have any plans to implement live streaming at the moment, but let me know if you fork this library to implement it.
