### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by pimboli** [moshisushi/hlsjs-ipfs-loader#6]
Hi seems that your demo isn't working anymore.

Do you know what's broken?

**Comment by moshisushi** [comment]
Thanks for reporting. I haven't had much time maintaining this library, but I've just merged a fix which should make the library work with latest IPFS. Let me know how it goes.

**Comment by moshisushi** [comment]
I tested with the latest version (0.1.3, just released), and works fine for me.

How I tested it:

- Run: npm install -g http-server
- From project root, run http-server
- In browser, go to http://localhost:8080/examples/basic_usage.html

I will clarify the instructions in the README
