### ISSUE TITLE
Readme needs a running example

### ISSUE THREAD

**Issue by georgyo** [moshisushi/hlsjs-ipfs-loader#8]
This is a pretty awesome, and works very well. However to see it in action requires several steps.

I took the example code and put into IPFS. This link or similar should endup in the readme.

https://ipfs.io/ipfs/QmZnCsPN9FLpgvcYbqNuKEJhqUuerbfkYS1VvL4dwLJDNW/

**Comment by moshisushi** [comment]
Thanks for this! Sorry for slow response. I will add this asap :)

**Comment by moshisushi** [comment]
@georgyo btw the link you posted doesn't seem to work for me :/ I suppose whatever example we use in the README needs to be pinned somewhere reliable.

**Comment by moshisushi** [comment]
@georgyo @ChristopheBougere Running example here: https://moshisushi.github.io/ipfs_hls_example.html, which is also linked from the README.
